# Generated by Django 2.2 on 2019-05-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcao',
            name='nome',
            field=models.CharField(help_text='Nome da função', max_length=50),
        ),
    ]
