# Generated by Django 2.2 on 2019-05-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcoes', '0002_auto_20190505_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcao',
            name='salario',
            field=models.CharField(blank=True, help_text='Salário Base', max_length=50, null=True),
        ),
    ]
