# Generated by Django 2.2 on 2019-04-18 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('funcionarios', '0002_auto_20190417_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='id_departamento',
            new_name='departamento',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='id_empresa',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa'),
        ),
    ]
