# Generated by Django 2.2 on 2019-04-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_auto_20190418_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(default=11111111111, help_text='CPF do funcionário', max_length=11),
            preserve_default=False,
        ),
    ]
