# Generated by Django 2.2 on 2019-05-06 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcoes', '0002_auto_20190505_1121'),
        ('funcionarios', '0007_auto_20190423_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='ag_pis',
            field=models.CharField(blank=True, help_text='Agência do pis', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='bairro',
            field=models.CharField(blank=True, help_text='Bairro', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='banco_pis',
            field=models.CharField(blank=True, help_text='Banco do pis', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='casado_bras',
            field=models.CharField(blank=True, help_text='Casado com Brasileiro(S/N)', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cbo',
            field=models.CharField(blank=True, help_text='CBO', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='celular',
            field=models.CharField(blank=True, help_text='Celular', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cep',
            field=models.CharField(blank=True, help_text='CEP', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cert_militar',
            field=models.CharField(blank=True, help_text='Certificado Militar', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cidade',
            field=models.CharField(blank=True, help_text='Cidade', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cnh',
            field=models.CharField(blank=True, help_text='CNH', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='complemento',
            field=models.CharField(blank=True, help_text='Complemento do endereço', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='contato1',
            field=models.CharField(blank=True, help_text='Primeiro Contato', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='contato2',
            field=models.CharField(blank=True, help_text='Segundo Contato', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ctps',
            field=models.CharField(blank=True, help_text='CTPS', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ctps_rural',
            field=models.CharField(blank=True, help_text='CTPS Rural', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(blank=True, help_text='Data de Admissão', null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_chegada',
            field=models.DateField(blank=True, help_text='Data de Chegada Brasil', null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_emissao',
            field=models.DateField(blank=True, help_text='Data de emissao', null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_nasc',
            field=models.DateField(blank=True, help_text='Data de Nascimento', null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_pis',
            field=models.DateField(blank=True, help_text='eemissao do pis', null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='email',
            field=models.CharField(blank=True, help_text='Email', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='endereco',
            field=models.CharField(blank=True, help_text='Endereço', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='estado_civil',
            field=models.CharField(blank=True, help_text='Estado Civil', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='estrangeiro',
            field=models.CharField(blank=True, help_text='Estrangeiro(S/N)', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='funcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='funcoes.Funcao'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nacionalidade',
            field=models.CharField(blank=True, help_text='Nacionalidade', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='naturalidade',
            field=models.CharField(blank=True, help_text='Naturalidade', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='naturalizado',
            field=models.CharField(blank=True, help_text='Naturalizado', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nome_conjuge',
            field=models.CharField(blank=True, help_text='Nome do Cônjuge', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nome_pai',
            field=models.CharField(blank=True, help_text='Nome do Pai', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='num_decreto',
            field=models.CharField(blank=True, help_text='Nº Decreto', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='num_dependentes',
            field=models.IntegerField(blank=True, help_text='Nº Dependentes', null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='numero',
            field=models.CharField(blank=True, help_text='Número do endereço', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='orgao',
            field=models.CharField(blank=True, help_text='Órgão emissor', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='pis',
            field=models.CharField(blank=True, help_text='Nº do Pis', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='qtd_filhos_bras',
            field=models.IntegerField(blank=True, help_text='Quantos Filhos Brasileiros', null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='rg',
            field=models.CharField(blank=True, help_text='RG do funcionário', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salário', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='secao',
            field=models.CharField(blank=True, help_text='Seção Eleitoral', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tel_contato1',
            field=models.CharField(blank=True, help_text='telefone Contato', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tel_contato2',
            field=models.CharField(blank=True, help_text='Telefone Contato', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefones', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tem_filhos_bras',
            field=models.CharField(blank=True, help_text='Filhos com Brasileiro(S/N)', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='titulo',
            field=models.CharField(blank=True, help_text='Título de Eleitor', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='uf',
            field=models.CharField(blank=True, help_text='UF', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='zona',
            field=models.CharField(blank=True, help_text='Zona Eleitoral', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(help_text='Nome do funcionário', max_length=50),
        ),
    ]
