# Generated by Django 2.2 on 2019-05-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0010_auto_20190507_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='nome_mae',
            field=models.CharField(blank=True, help_text='Nome da Mãe', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('S', 'Solteiro'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viúvo'), ('V', 'Outros')], max_length=1, null=True),
        ),
    ]
