# Generated by Django 2.2 on 2019-05-07 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_auto_20190417_1017'),
        ('funcionarios', '0011_auto_20190507_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_pis',
            field=models.DateField(blank=True, help_text='emissao do pis', null=True),
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='departamentos',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='departamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='departamentos.Departamento'),
        ),
    ]
