# Generated by Django 2.2 on 2019-05-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0012_auto_20190507_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='casado_bras',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], help_text='Casado com Brasileiro(S/N)', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='estrangeiro',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], help_text='Estrangeiro(S/N)', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='naturalizado',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], help_text='Naturalizado', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tem_filhos_bras',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], help_text='Filhos com Brasileiro(S/N)', max_length=1, null=True),
        ),
    ]
