# Generated by Django 2.2 on 2019-05-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0014_auto_20190513_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, help_text='Email', max_length=100, null=True),
        ),
    ]
