# Generated by Django 2.2 on 2019-05-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0015_auto_20190514_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(help_text='CPF do funcionário', max_length=11),
        ),
    ]
