# Generated by Django 2.2 on 2019-05-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0016_auto_20190515_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(help_text='CPF do funcionário', max_length=14),
        ),
    ]
