# Generated by Django 2.2 on 2019-06-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0017_auto_20190515_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_movto',
            field=models.DateField(blank=True, help_text='Data de Movimentação', null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(help_text='CPF do funcionário', max_length=14, unique=True),
        ),
    ]
