# Generated by Django 2.2 on 2019-12-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0018_auto_20190613_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cep',
            field=models.CharField(blank=True, help_text='CEP', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='ctps',
            field=models.CharField(blank=True, help_text='CTPS', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='ctps_rural',
            field=models.CharField(blank=True, help_text='CTPS Rural', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='titulo',
            field=models.CharField(blank=True, help_text='Título de Eleitor', max_length=15, null=True),
        ),
    ]
