# Generated by Django 2.2 on 2019-12-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Descrição do horário', max_length=50)),
                ('hora_entrada', models.TimeField(blank=True, help_text='Hora de entrada', max_length=4, null=True)),
                ('hora_saida', models.TimeField(blank=True, help_text='Hora de saida', max_length=5, null=True)),
                ('intervalo_saida', models.TimeField(blank=True, help_text='Hora de saída do intervalo', max_length=5, null=True)),
                ('intervalo_entrada', models.TimeField(blank=True, help_text='Hora de entrada do intervalo', max_length=5, null=True)),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
    ]
