# Generated by Django 2.2 on 2019-06-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20190613_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='id',
            field=models.IntegerField(help_text='ID', primary_key=True, serialize=False),
        ),
    ]
