# Generated by Django 2.2 on 2019-04-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(default=11111111111111, help_text='CNPJ da empresa', max_length=14),
            preserve_default=False,
        ),
    ]
