# Generated by Django 2.2 on 2019-04-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(blank=True, help_text='Bairro', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cep',
            field=models.CharField(blank=True, help_text='CEP', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(blank=True, help_text='Cidade', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='complemento',
            field=models.CharField(blank=True, help_text='Complemento do endereço', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.CharField(blank=True, help_text='Email', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco',
            field=models.CharField(blank=True, help_text='Endereço', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fantasia',
            field=models.CharField(blank=True, help_text='Nome fantasia', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='insc_est',
            field=models.CharField(blank=True, help_text='Inscrição Estadual', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='insc_mun',
            field=models.CharField(blank=True, help_text='Inscrição Municipal', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero',
            field=models.CharField(blank=True, help_text='Número do endereço', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefones',
            field=models.CharField(blank=True, help_text='Telefones', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='uf',
            field=models.CharField(blank=True, help_text='UF', max_length=2, null=True),
        ),
    ]
