# Generated by Django 2.2 on 2019-05-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_auto_20190527_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(help_text='CNPJ da empresa', max_length=18, unique=True),
        ),
    ]
