# Generated by Django 2.2 on 2019-05-17 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0017_auto_20190515_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependentes_func',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do dependente', max_length=50)),
                ('parentesto', models.CharField(blank=True, choices=[('C', 'Cônjuge OU Companheiro(a)'), ('F', 'Filho(a) ou enteado(a), até 21 anos'), ('E', 'Filho(a) ou enteado(a) Estudante, até 24 anos de idade'), ('I', 'Irmão(ã), neto(a) ou bisneto(a)'), ('A', 'Pais, avós e bisavós'), ('M', 'Menor pobre até 21 anos'), ('I', 'Pessoa absolutamente incapaz'), ('O', 'Outros')], help_text='Grau de Parentesco', max_length=1, null=True)),
                ('data_nasc', models.DateField(blank=True, help_text='emissao do pis', null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionarios.Funcionario')),
            ],
        ),
    ]
