# Generated by Django 2.2 on 2019-05-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependentes_func', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependentes_func',
            old_name='parentesto',
            new_name='parentesco',
        ),
    ]
