# Generated by Django 2.2 on 2019-07-10 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependentes_func', '0003_dependentes_func_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependentes_func',
            name='cpf',
        ),
    ]
