# Generated by Django 2.2 on 2019-12-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependentes_func', '0007_dependentes_func_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependentes_func',
            name='paga_pensao',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], help_text='Paga Pensão(S/N)', max_length=1, null=True),
        ),
    ]
