# Generated by Django 2.2 on 2019-06-07 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        ('funcionarios', '0017_auto_20190515_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lancamento', models.DateField(auto_now_add=True, verbose_name='Lançado em')),
                ('data_evento', models.DateField(blank=True, help_text='Data do Evento', null=True)),
                ('data_para_conclusao', models.DateField(blank=True, help_text='Data para Conclusão', null=True)),
                ('concluido_em', models.DateField(blank=True, help_text='Concluído em', null=True)),
                ('observacao', models.CharField(blank=True, help_text='Observação', max_length=200, null=True)),
                ('login', models.CharField(blank=True, help_text='login que lançou', max_length=20, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.Evento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionarios.Funcionario')),
            ],
        ),
    ]
