# Generated by Django 2.2 on 2019-12-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0002_auto_20190613_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='arquivo_mov',
            field=models.FileField(blank=True, null=True, upload_to='documento_mov'),
        ),
    ]
