# Generated by Django 2.2 on 2019-06-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_auto_20190417_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['nome']},
        ),
    ]
