# Generated by Django 2.2 on 2019-05-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_auto_20190514_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='id_func',
            new_name='funcionario',
        ),
    ]
