# Generated by Django 2.2 on 2019-05-21 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0017_auto_20190515_1635'),
        ('empresas', '0003_auto_20190423_1957'),
        ('funcoes', '0003_funcao_salario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lancamento', models.DateField(auto_now_add=True, verbose_name='criado em')),
                ('data_admissao', models.DateField(blank=True, help_text='Data de Admissão', null=True)),
                ('data_registro', models.DateField(blank=True, help_text='Data de Registro', null=True)),
                ('optante_fgts', models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], help_text='Optante FGTS(S/N)', max_length=1, null=True)),
                ('data_opcao', models.DateField(blank=True, help_text='Data de Opção', null=True)),
                ('data_retratacao', models.DateField(blank=True, help_text='Data de Retratação', null=True)),
                ('banco_depositario', models.CharField(blank=True, help_text='Banco do FGTS', max_length=3, null=True)),
                ('em_experiencia', models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], help_text='Em experiência(S/N)', max_length=1, null=True)),
                ('prazo_experiencia', models.IntegerField(blank=True, help_text='Prazo de Experiência', null=True)),
                ('vencto_experiencia', models.DateField(blank=True, help_text='Vencimento da Experiência', null=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, help_text='Salário', max_digits=10, null=True)),
                ('data_inicio_aviso', models.DateField(blank=True, help_text='Data de Início do Aviso', null=True)),
                ('data_fim_aviso', models.DateField(blank=True, help_text='Data Final do Aviso', null=True)),
                ('motivo', models.CharField(blank=True, help_text='Motivo da Demissão', max_length=100, null=True)),
                ('data_demissao', models.DateField(blank=True, help_text='Data de Demissão', null=True)),
                ('data_homologacao', models.DateField(blank=True, help_text='Data de Homologação', null=True)),
                ('data_pagamento', models.DateField(blank=True, help_text='Data de Pagamento', null=True)),
                ('data_mov', models.DateTimeField(auto_now_add=True, help_text='Data do Movimento')),
                ('tipo_ope', models.CharField(blank=True, help_text='Tipo de Operação', max_length=1, null=True)),
                ('contratado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='r_contratado_por', to='funcionarios.Funcionario')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa')),
                ('funcao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='funcoes.Funcao')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='r_funcionario', to='funcionarios.Funcionario')),
                ('login', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
