# Generated by Django 2.2 on 2019-05-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='login',
            field=models.CharField(blank=True, help_text='Motivo da Demissão', max_length=20, null=True),
        ),
    ]
