# Generated by Django 2.2 on 2019-06-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_auto_20190524_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ['empresa', 'funcionario', 'data_lancamento']},
        ),
    ]
