# Generated by Django 2.2 on 2019-12-19 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
        ('contratos', '0003_auto_20190613_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='horarios.Horario'),
        ),
    ]
