# Generated by Django 2.2 on 2019-12-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_contrato_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='data_inicio_horario',
            field=models.DateField(blank=True, help_text='Data de Início no Horário', null=True),
        ),
    ]
