# Generated by Django 2.2 on 2020-01-03 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios_func', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficios_func',
            name='funcionario',
        ),
    ]
